server:
  port: 8101
eureka:
  instance:
    hostname: http://localhost:8001
    defaultZone: http://localhost:8001
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8001
  server:
    #保护模式
    enable-self-preservation: true
    #清理无效服务时间 默认60秒
    eviction-interval-timer-in-ms: 5000
spring:
  application:
    name: zuul-dev1