server:
  port: 8100

spring:
  application:
      name: vservice-zuul-dev

eureka:
  instance:
    hostname: zuul-dev
    instance-id: http://localhost:${server.port}
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  server:
    #保护模式
    enable-self-preservation: true
    #清理无效服务时间 默认60秒
    eviction-interval-timer-in-ms: 10000

